#! /bin/bash
# v0.5.2

RESTORE='\033[0m'

RED='\033[00;31m'
GREEN='\033[00;32m'
BLUE='\033[00;34m'
LRED='\033[01;31m'
LGREEN='\033[01;32m'
LBLUE='\033[01;34m'

error() { echo -e ${LRED}"! "${@}${RESTORE}; }
notice() { echo -e ${LBLUE}${@}${RESTORE}; }
ok() { echo -e ${LGREEN}${@}${RESTORE}; }

if [ $(which sha1sum) ]
then
  sha_util=$(which sha1sum)
elif [ $(which shasum) ]
then
  sha_util=$(which shasum)
else
  error "No utility to calculate SHA checksums found. Exiting."
  exit 1
fi

notice "Original hashes:"
shopt -s nocaseglob

# extract expected hashes from PKL
grep 'OriginalFileName\|Hash' *PKL*.xml | sed -n 's/[^>]*>\([^<]*\)<.*/\1/p' | sed 'N;s/\n/ /; s/\([^ ]*\) \(.*\)/\2 \1/' | sort > original.tmp

cat original.tmp
notice "Checking hashes of DCP..."

# calculate actual hashes from files
for i in * */*; do [ -f "$i" ] && $sha_util "$i" | cut -f1 -d\ | xxd -r -p | base64 | sed "s#^#"${i}" #" | tee -a copy.tmp ; done

# sort and compare
grep copy.tmp -v -e 'ASSETMAP' -e 'PKL_' -e 'VOLINDEX' -e 'original.tmp' | sort -o copy.tmp

if diff original.tmp copy.tmp
then
  ok "\tDCP verification successful."
else
  error "\tDCP verification failed."
fi

# cleanup
rm original.tmp copy.tmp
