#!/bin/bash

# Domingo Stephan
# Version 0.3

[ $# -eq 0 ] || [ $# -ne 3 ] && {
  echo ""
  echo "rename for j2c image sequences."
  echo "Usage: $0 prefix base step"
  exit 1
}

prefix="$1"
shift

base_n="$1"
shift

step="$1"
shift

n=$base_n

for file in *.j2c ; do
    formatted_n=$(printf "%07d" $n)
    # re-use original file extension while we're at it.
    mv "$file" "${prefix}${formatted_n}.${file##*.}"
    let n=n+$step
done
